#!/bin/sh

(
	./extract-idax sf/idax\ Counts\ */*.txt
	./extract-sfmta sf/SFMTA\ Staff\ Counts/*.txt
) | ./geocode > counts-sf.csv

cat sf.csv | ./process-sf | ./geocode > counts-sf-misc.csv

./extract-db > counts-sf-db.csv

./extract-idax misc/*.txt | ./geocode-misc > counts-misc.csv
./extract-idax sanjose/*.txt | ./geocode-misc > counts-sanjose.csv
