#!/usr/bin/perl

while (<>) {
	chomp;

	if (/^http*/) {
		$url = $_;
		next;
	}

	($name, $date, $time, $count) = split(/,/);

	if ($count ne "") {
		while ($count =~ s/([0-9]+) \+ ([0-9]+)$//) {
			$count .= sprintf("%d", $1 + $2);
		}

		print "$url,$name,(extrapolated),$date,$time,,,,,,,,,,,,,";

		for ($i = 0; $i < 4; $i++) {
			print $count / 4;
			print ",";
		}

		print "\n";
	}
}
